upstream_url = "https://download.clearlinux.org"
bundles_url = "https://github.com/clearlinux/clr-bundles"

[mixer]
  workspace = "/home/user/clearlinux/mix"

[paths]
  bundle_repository = "/home/user/clearlinux/projects/clr-bundles"
  local_rpms = "/home/user/clearlinux/repo"
  cache = "/home/user/clearlinux/data"
